### ISSUE TITLE
Опыт по поводу мультиплеера.

### ISSUE THREAD

**Issue by Mordentary** [ANTIoffz/FortsModLoader#1]
Привет. Получалось ли у тебя запустить моды с друзьями? У меня только в приватной игре можно их включить. Если есть какое-то решение... я был бы рад узнать

**Comment by ANTIoffz** [comment]
Да, я изначально для этого и делал, если что то не получается могу помочь

**Comment by Mordentary** [comment]
Спасибо. Как я понял, единственный способ чтобы моды работали в мультиплеере - заменять стандартные моды после запуска игры. Ну я и написал программу, которая это делает.. За скелет взял твой скрипт.

**Comment by Mordentary** [comment]
Я только что посмотрел твой скрипт:) Только сейчас понял, что ты это и делаешь после ентера, лол). Кстати, как ты решил проблему, что моды в списке в самом фортсе идут не в порядке их замены в папке модс. 
Я просто отсортировал список свободных для замены чтобы он совпадал с игрой. То есть стандартные моды просто включаешь по порядку..

**Comment by ANTIoffz** [comment]
Не совсем понял если честно) Я просто заменяю файлы стандартного мода на файлы нужного, а дальше уже просто вспоминаю какие выбирал для замены

**Comment by Mordentary** [comment]
Да, да. Кстати, в итоге наткнулся на проблему, что если в тиме больше двух человек один из них вылетал с десинком. Пришлось просто купить игру)
